version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mars
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - mars-db:/var/lib/mars-db
volumes:
  mars-db:
